apiVersion: v1
kind: Service
metadata:
  name: pritunl
  namespace: infrastructure
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 1194
      name: openvpn
  selector:
    app: pritunl

